### ISSUE TITLE
Should --keep-coastlines be kept?

### ISSUE THREAD

**Issue by hixi** [geometalab/osm-world-db#10]
Should the former `--keep-coastlines` be kept or was it right to remove it, since it breaks often?

If not storing the coastlines, should a replacement be included?

**Comment by das-g** [comment]
> [...] since it breaks often [...]

What breaks often? The coastlines in OSM or the `--keep-coastlines` option? (I know about the former, but your phrasing makes it sound like the latter breaks.)

**Comment by hixi** [comment]
The coastlines in OSM break often.
IMO, this has been decided as "do not include coastlines directly" through issues geometalab/osmaxx-conversion-service#97 and geometalab/osmaxx-conversion-service#99
